{
    "msg" : "",
    "obj" : [
    {
        "answerA": "没有",
        "answerB": "偶尔",
        "answerC": "有时",
        "answerD": "经常",
        "answerE": "总是",
        "asnwerAScore": 5,
        "asnwerBScore": 4,
        "asnwerCScore": 3,
        "asnwerDScore": 2,
        "asnwerEScore": 1,
        "id": "d7e3874d-362e-47e4-a003-080321b849d1",
        "num": 44,
        "question": "便秘",
        "type": 1
    },
    {
        "answerA": "没有",
        "answerB": "偶尔",
        "answerC": "有时",
        "answerD": "经常",
        "answerE": "总是",
        "asnwerAScore": 5,
        "asnwerBScore": 4,
        "asnwerCScore": 3,
        "asnwerDScore": 2,
        "asnwerEScore": 1,
        "id": "f8ab672c-3f81-4e85-83cb-2d92f4b44572",
        "num": 45,
        "question": "盗汗或多汗",
        "type": 1
    },
    {
        "answerA": "没有",
        "answerB": "偶尔",
        "answerC": "有时",
        "answerD": "经常",
        "answerE": "总是",
        "asnwerAScore": 5,
        "asnwerBScore": 4,
        "asnwerCScore": 3,
        "asnwerDScore": 2,
        "asnwerEScore": 1,
        "id": "33f26b4b-43f6-415f-96d4-15424db22cdf",
        "num": 46,
        "question": "恶心或反酸",
        "type": 1
    },
    {
        "answerA": "没有",
        "answerB": "偶尔",
        "answerC": "有时",
        "answerD": "经常",
        "answerE": "总是",
        "asnwerAScore": 5,
        "asnwerBScore": 4,
        "asnwerCScore": 3,
        "asnwerDScore": 2,
        "asnwerEScore": 1,
        "id": "30dec745-5a2a-4ec1-bd83-0d391a56b345",
        "num": 47,
        "question": "腹泻或腹痛",
        "type": 1
    },
    {
        "answerA": "没有",
        "answerB": "偶尔",
        "answerC": "有时",
        "answerD": "经常",
        "answerE": "总是",
        "asnwerAScore": 5,
        "asnwerBScore": 4,
        "asnwerCScore": 3,
        "asnwerDScore": 2,
        "asnwerEScore": 1,
        "id": "1d11c218-9679-4d01-bda2-279d22cfa07c",
        "num": 48,
        "question": "明显的关节痛",
        "type": 1
    },
    {
        "answerA": "没有",
        "answerB": "偶尔",
        "answerC": "有时",
        "answerD": "经常",
        "answerE": "总是",
        "asnwerAScore": 5,
        "asnwerBScore": 4,
        "asnwerCScore": 3,
        "asnwerDScore": 2,
        "asnwerEScore": 1,
        "id": "63d7981c-b9c5-4366-95c7-8cd9b39f9223",
        "num": 49,
        "question": "明显的咳嗽、咳痰",
        "type": 1
    },
    {
        "answerA": "没有",
        "answerB": "偶尔",
        "answerC": "有时",
        "answerD": "经常",
        "answerE": "总是",
        "asnwerAScore": 5,
        "asnwerBScore": 4,
        "asnwerCScore": 3,
        "asnwerDScore": 2,
        "asnwerEScore": 1,
        "id": "2e5c4bf4-0dfb-439b-8cc9-0daf8fc92664",
        "num": 50,
        "question": "咳痰带血或咯血",
        "type": 1
    },
    {
        "answerA": "没有",
        "answerB": "偶尔",
        "answerC": "有时",
        "answerD": "经常",
        "answerE": "总是",
        "asnwerAScore": 5,
        "asnwerBScore": 4,
        "asnwerCScore": 3,
        "asnwerDScore": 2,
        "asnwerEScore": 1,
        "id": "2beb998c-c016-4d60-a4e3-889bca3664dd",
        "num": 51,
        "question": "尿频、尿急、尿痛或尿血",
        "type": 1
    },
    {
        "answerA": "没有",
        "answerB": "偶尔",
        "answerC": "有时",
        "answerD": "经常",
        "answerE": "总是",
        "asnwerAScore": 5,
        "asnwerBScore": 4,
        "asnwerCScore": 3,
        "asnwerDScore": 2,
        "asnwerEScore": 1,
        "id": "d4e83201-2cf6-4369-86f7-e8d7645706f9",
        "num": 52,
        "question": "疲劳乏力",
        "type": 1
    },
    {
        "answerA": "没有",
        "answerB": "偶尔",
        "answerC": "有时",
        "answerD": "经常",
        "answerE": "总是",
        "asnwerAScore": 5,
        "asnwerBScore": 4,
        "asnwerCScore": 3,
        "asnwerDScore": 2,
        "asnwerEScore": 1,
        "id": "e4faa05b-6f69-4635-a6ab-5b6c8fda1b26",
        "num": 53,
        "question": "失眠",
        "type": 1
    },
    {
        "answerA": "没有",
        "answerB": "偶尔",
        "answerC": "有时",
        "answerD": "经常",
        "answerE": "总是",
        "asnwerAScore": 5,
        "asnwerBScore": 4,
        "asnwerCScore": 3,
        "asnwerDScore": 2,
        "asnwerEScore": 1,
        "id": "04306f0e-9d6e-4647-bf1f-6484db5b151e",
        "num": 54,
        "question": "正常作息下还是感觉困",
        "type": 1
    },
    {
        "answerA": "没有",
        "answerB": "偶尔",
        "answerC": "有时",
        "answerD": "经常",
        "answerE": "总是",
        "asnwerAScore": 5,
        "asnwerBScore": 4,
        "asnwerCScore": 3,
        "asnwerDScore": 2,
        "asnwerEScore": 1,
        "id": "8c13e589-d658-4864-a937-83d086887294",
        "num": 55,
        "question": "食欲不振、消化不良",
        "type": 1
    },
    {
        "answerA": "没有",
        "answerB": "偶尔",
        "answerC": "有时",
        "answerD": "经常",
        "answerE": "总是",
        "asnwerAScore": 5,
        "asnwerBScore": 4,
        "asnwerCScore": 3,
        "asnwerDScore": 2,
        "asnwerEScore": 1,
        "id": "e6c57be8-090f-4588-ad84-38876c8b13c9",
        "num": 56,
        "question": "明显的手足发麻或刺痛",
        "type": 1
    },
    {
        "answerA": "没有",
        "answerB": "偶尔",
        "answerC": "有时",
        "answerD": "经常",
        "answerE": "总是",
        "asnwerAScore": 5,
        "asnwerBScore": 4,
        "asnwerCScore": 3,
        "asnwerDScore": 2,
        "asnwerEScore": 1,
        "id": "537548e5-585c-4f8b-90e3-e21ceb55dede",
        "num": 57,
        "question": "头昏或头痛",
        "type": 1
    },
    {
        "answerA": "没有",
        "answerB": "偶尔",
        "answerC": "有时",
        "answerD": "经常",
        "answerE": "总是",
        "asnwerAScore": 5,
        "asnwerBScore": 4,
        "asnwerCScore": 3,
        "asnwerDScore": 2,
        "asnwerEScore": 1,
        "id": "475f4077-35bf-4cfb-9d23-384618ea502a",
        "num": 58,
        "question": "性欲减退",
        "type": 1
    },
    {
        "answerA": "没有",
        "answerB": "偶尔",
        "answerC": "有时",
        "answerD": "经常",
        "answerE": "总是",
        "asnwerAScore": 5,
        "asnwerBScore": 4,
        "asnwerCScore": 3,
        "asnwerDScore": 2,
        "asnwerEScore": 1,
        "id": "76cc94a2-e6b2-4d0c-a523-2943dcd04241",
        "num": 59,
        "question": "眩晕",
        "type": 1
    },
    {
        "answerA": "没有",
        "answerB": "偶尔",
        "answerC": "有时",
        "answerD": "经常",
        "answerE": "总是",
        "asnwerAScore": 5,
        "asnwerBScore": 4,
        "asnwerCScore": 3,
        "asnwerDScore": 2,
        "asnwerEScore": 1,
        "id": "9becd38e-c55a-4359-9e0e-5e7eeb0afea8",
        "num": 60,
        "question": "视力下降",
        "type": 1
    },
    {
        "answerA": "没有",
        "answerB": "偶尔",
        "answerC": "有时",
        "answerD": "经常",
        "answerE": "总是",
        "asnwerAScore": 5,
        "asnwerBScore": 4,
        "asnwerCScore": 3,
        "asnwerDScore": 2,
        "asnwerEScore": 1,
        "id": "f1006fab-51d5-47df-b7da-bc0ca4facb64",
        "num": 61,
        "question": "听力下降",
        "type": 1
    },
    {
        "answerA": "没有",
        "answerB": "偶尔",
        "answerC": "有时",
        "answerD": "经常",
        "answerE": "总是",
        "asnwerAScore": 5,
        "asnwerBScore": 4,
        "asnwerCScore": 3,
        "asnwerDScore": 2,
        "asnwerEScore": 1,
        "id": "1144adb6-1460-4c63-aa31-b12e354ef55e",
        "num": 62,
        "question": "明显的腰痛",
        "type": 1
    },
    {
        "answerA": "没有",
        "answerB": "很轻",
        "answerC": "中等",
        "answerD": "偏重",
        "answerE": "严重",
        "asnwerAScore": 5,
        "asnwerBScore": 4,
        "asnwerCScore": 3,
        "asnwerDScore": 2,
        "asnwerEScore": 1,
        "id": "4f6f45c4-b781-441d-b036-1db8895ec563",
        "num": 63,
        "question": "与他人交往时有不自在感或自卑感",
        "type": 2
    },
    {
        "answerA": "没有",
        "answerB": "很轻",
        "answerC": "中等",
        "answerD": "偏重",
        "answerE": "严重",
        "asnwerAScore": 5,
        "asnwerBScore": 4,
        "asnwerCScore": 3,
        "asnwerDScore": 2,
        "asnwerEScore": 1,
        "id": "6517c956-3e98-4d36-8baf-c44e50f13783",
        "num": 64,
        "question": "感到自己没什么价值，前途没希望",
        "type": 2
    },
    {
        "answerA": "没有",
        "answerB": "很轻",
        "answerC": "中等",
        "answerD": "偏重",
        "answerE": "严重",
        "asnwerAScore": 5,
        "asnwerBScore": 4,
        "asnwerCScore": 3,
        "asnwerDScore": 2,
        "asnwerEScore": 1,
        "id": "4f90aa45-80c2-4a57-a0f1-16368a248f31",
        "num": 65,
        "question": "容易感到紧张或惊恐",
        "type": 2
    },
    {
        "answerA": "没有",
        "answerB": "很轻",
        "answerC": "中等",
        "answerD": "偏重",
        "answerE": "严重",
        "asnwerAScore": 5,
        "asnwerBScore": 4,
        "asnwerCScore": 3,
        "asnwerDScore": 2,
        "asnwerEScore": 1,
        "id": "f7f5f3c4-881a-4b02-9259-511800c1f10f",
        "num": 66,
        "question": "有摔东西的想法或者打人的冲动",
        "type": 2
    },
    {
        "answerA": "没有",
        "answerB": "很轻",
        "answerC": "中等",
        "answerD": "偏重",
        "answerE": "严重",
        "asnwerAScore": 5,
        "asnwerBScore": 4,
        "asnwerCScore": 3,
        "asnwerDScore": 2,
        "asnwerEScore": 1,
        "id": "096bea8d-8185-4e4c-a566-b9785a889a88",
        "num": 67,
        "question": "害怕单独出门或去空旷的场所",
        "type": 2
    },
    {
        "answerA": "没有",
        "answerB": "很轻",
        "answerC": "中等",
        "answerD": "偏重",
        "answerE": "严重",
        "asnwerAScore": 5,
        "asnwerBScore": 4,
        "asnwerCScore": 3,
        "asnwerDScore": 2,
        "asnwerEScore": 1,
        "id": "90969677-9990-4d40-946e-5a979c0d44f1",
        "num": 68,
        "question": "觉得多数人不可信任，认为别人想占您的便宜",
        "type": 2
    },
    {
        "answerA": "没有",
        "answerB": "很轻",
        "answerC": "中等",
        "answerD": "偏重",
        "answerE": "严重",
        "asnwerAScore": 5,
        "asnwerBScore": 4,
        "asnwerCScore": 3,
        "asnwerDScore": 2,
        "asnwerEScore": 1,
        "id": "f2735c6f-f7cb-4f9f-8e64-ad479c563e9d",
        "num": 69,
        "question": "感觉心情不好、情绪低落",
        "type": 2
    },
    {
        "answerA": "没有",
        "answerB": "很轻",
        "answerC": "中等",
        "answerD": "偏重",
        "answerE": "严重",
        "asnwerAScore": 5,
        "asnwerBScore": 4,
        "asnwerCScore": 3,
        "asnwerDScore": 2,
        "asnwerEScore": 1,
        "id": "a1086289-84b9-4b83-852c-5309d6ddf6d3",
        "num": 70,
        "question": "无缘无故的突然感到害怕",
        "type": 2
    },
    {
        "answerA": "没有",
        "answerB": "很轻",
        "answerC": "中等",
        "answerD": "偏重",
        "answerE": "严重",
        "asnwerAScore": 5,
        "asnwerBScore": 4,
        "asnwerCScore": 3,
        "asnwerDScore": 2,
        "asnwerEScore": 1,
        "id": "9e01323e-e28b-4c0e-88fc-70412bd5bf2f",
        "num": 71,
        "question": "感到坐立不安心神不定",
        "type": 2
    },
    {
        "answerA": "没有",
        "answerB": "很轻",
        "answerC": "中等",
        "answerD": "偏重",
        "answerE": "严重",
        "asnwerAScore": 5,
        "asnwerBScore": 4,
        "asnwerCScore": 3,
        "asnwerDScore": 2,
        "asnwerEScore": 1,
        "id": "ca0d8da8-06d9-4e5f-b26d-e5cbcb388155",
        "num": 72,
        "question": "易怒或莫名地大发脾气，没有耐性",
        "type": 2
    },
    {
        "answerA": "没有",
        "answerB": "很轻",
        "answerC": "中等",
        "answerD": "偏重",
        "answerE": "严重",
        "asnwerAScore": 5,
        "asnwerBScore": 4,
        "asnwerCScore": 3,
        "asnwerDScore": 2,
        "asnwerEScore": 1,
        "id": "8f087645-efe9-4596-bbb0-6b2908b5e5eb",
        "num": 73,
        "question": "感到孤独、苦闷，觉得活着的累",
        "type": 2
    },
    {
        "answerA": "没有",
        "answerB": "很轻",
        "answerC": "中等",
        "answerD": "偏重",
        "answerE": "严重",
        "asnwerAScore": 5,
        "asnwerBScore": 4,
        "asnwerCScore": 3,
        "asnwerDScore": 2,
        "asnwerEScore": 1,
        "id": "1e507b44-4076-4e6e-9b91-2b9eec5d803a",
        "num": 74,
        "question": "敏感多疑",
        "type": 2
    },
    {
        "answerA": "没有",
        "answerB": "很轻",
        "answerC": "中等",
        "answerD": "偏重",
        "answerE": "严重",
        "asnwerAScore": 5,
        "asnwerBScore": 4,
        "asnwerCScore": 3,
        "asnwerDScore": 2,
        "asnwerEScore": 1,
        "id": "17af6be7-66c5-4732-b648-de5a615a12f8",
        "num": 75,
        "question": "记忆力减退",
        "type": 2
    },
    {
        "answerA": "没有",
        "answerB": "很轻",
        "answerC": "中等",
        "answerD": "偏重",
        "answerE": "严重",
        "asnwerAScore": 5,
        "asnwerBScore": 4,
        "asnwerCScore": 3,
        "asnwerDScore": 2,
        "asnwerEScore": 1,
        "id": "b786e81a-440a-469b-bfa5-8c59a39c91e1",
        "num": 76,
        "question": "注意力集中有困难",
        "type": 2
    },
    {
        "answerA": "没有",
        "answerB": "很轻",
        "answerC": "中等",
        "answerD": "偏重",
        "answerE": "严重",
        "asnwerAScore": 5,
        "asnwerBScore": 4,
        "asnwerCScore": 3,
        "asnwerDScore": 2,
        "asnwerEScore": 1,
        "id": "a6058ea2-b065-4540-bc3f-99304653a811",
        "num": 77,
        "question": "对新事物不感兴趣，学习能力差",
        "type": 2
    },
    {
        "answerA": "很不满意",
        "answerB": "较不满意",
        "answerC": "一般",
        "answerD": "较满意",
        "answerE": "很满意",
        "asnwerAScore": 1,
        "asnwerBScore": 2,
        "asnwerCScore": 3,
        "asnwerDScore": 4,
        "asnwerEScore": 5,
        "id": "16b10047-9862-4237-9c2f-3ea685f156c8",
        "num": 78,
        "question": "对单位（学校）中的人际关系是否满意？",
        "type": 3
    },
    {
        "answerA": "很不融洽",
        "answerB": "较不融洽",
        "answerC": "一般",
        "answerD": "较融洽",
        "answerE": "很融洽",
        "asnwerAScore": 1,
        "asnwerBScore": 2,
        "asnwerCScore": 3,
        "asnwerDScore": 4,
        "asnwerEScore": 5,
        "id": "3c1ac3da-ed02-408e-9d40-fd71178b95d5",
        "num": 79,
        "question": "与同事（同学）之间关系是否融洽？",
        "type": 3
    },
    {
        "answerA": "很差 ",
        "answerB": "较差",
        "answerC": "一般",
        "answerD": "较好",
        "answerE": "很好",
        "asnwerAScore": 1,
        "asnwerBScore": 2,
        "asnwerCScore": 3,
        "asnwerDScore": 4,
        "asnwerEScore": 5,
        "id": "b1720209-1a18-4bb2-adf8-db9a86cec762",
        "num": 80,
        "question": "交往能力、沟通能力",
        "type": 3
    },
    {
        "answerA": "根本不能",
        "answerB": "很少能",
        "answerC": "有时能",
        "answerD": "多数能",
        "answerE": "完全能够",
        "asnwerAScore": 1,
        "asnwerBScore": 2,
        "asnwerCScore": 3,
        "asnwerDScore": 4,
        "asnwerEScore": 5,
        "id": "ac43d874-c489-4bca-8bd3-d251f93f0e48",
        "num": 81,
        "question": "能否妥善处理发生在自己身上的不愉快事情",
        "type": 3
    },
    {
        "answerA": "很不满意",
        "answerB": "较不满意",
        "answerC": "一般 ",
        "answerD": "较满意 ",
        "answerE": "很满意",
        "asnwerAScore": 1,
        "asnwerBScore": 2,
        "asnwerCScore": 3,
        "asnwerDScore": 4,
        "asnwerEScore": 5,
        "id": "fe62e779-f258-4a6c-bf67-23b16cebdfd4",
        "num": 82,
        "question": "对自己的的社会角色及工作能力是否满意？",
        "type": 3
    },
    {
        "answerA": "很不和睦",
        "answerB": "较不和睦",
        "answerC": "一般 ",
        "answerD": "较和睦",
        "answerE": "很和睦",
        "asnwerAScore": 1,
        "asnwerBScore": 2,
        "asnwerCScore": 3,
        "asnwerDScore": 4,
        "asnwerEScore": 5,
        "id": "9647d494-2a2c-4318-8e29-4a652d45e852",
        "num": 83,
        "question": "家庭生活是否和睦",
        "type": 3
    },
    {
        "answerA": "无",
        "answerB": "很少",
        "answerC": "一般 ",
        "answerD": "很多",
        "answerE": "非常多（10个以上）",
        "asnwerAScore": 1,
        "asnwerBScore": 2,
        "asnwerCScore": 3,
        "asnwerDScore": 4,
        "asnwerEScore": 5,
        "id": "f4f0eaca-b92f-419e-95da-343f3bcd4366",
        "num": 84,
        "question": "与您关系密切的亲人、朋友多吗？",
        "type": 3
    },
    {
        "answerA": "无",
        "answerB": "很少",
        "answerC": "一般 ",
        "answerD": "很多",
        "answerE": "非常多",
        "asnwerAScore": 1,
        "asnwerBScore": 2,
        "asnwerCScore": 3,
        "asnwerDScore": 4,
        "asnwerEScore": 5,
        "id": "0cf076f2-d8d0-464c-adcd-7c88f30bc252",
        "num": 85,
        "question": "在您遇到急难情况时，得到支持和帮助的来源多吗？",
        "type": 3
    },
    {
        "answerA": "无",
        "answerB": "很少",
        "answerC": "一般 ",
        "answerD": "很多",
        "answerE": "非常多",
        "asnwerAScore": 1,
        "asnwerBScore": 2,
        "asnwerCScore": 3,
        "asnwerDScore": 4,
        "asnwerEScore": 5,
        "id": "329d1519-cff4-4842-80a8-d7932dfa5b28",
        "num": 86,
        "question": "在您遇到烦恼时，是否有较多的倾诉对象或者求助方式？",
        "type": 3
    },
    {
        "answerA": "无",
        "answerB": "很少",
        "answerC": "一般 ",
        "answerD": "很多",
        "answerE": "非常多（10个以上）",
        "asnwerAScore": 1,
        "asnwerBScore": 2,
        "asnwerCScore": 3,
        "asnwerDScore": 4,
        "asnwerEScore": 5,
        "id": "d97a6ed7-6c8c-4d09-a362-e9dd3ef806f9",
        "num": 87,
        "question": "您有可以与您分享快乐和忧伤的朋友吗？",
        "type": 3
    },
    {
        "answerA": "根本不能",
        "answerB": "很少能",
        "answerC": "有时能",
        "answerD": "多数能",
        "answerE": "完全能够",
        "asnwerAScore": 1,
        "asnwerBScore": 2,
        "asnwerCScore": 3,
        "asnwerDScore": 4,
        "asnwerEScore": 5,
        "id": "b2c3419e-d1ee-404b-8c53-74e595016641",
        "num": 88,
        "question": "在需要时，您能获得家人的帮助和支持？",
        "type": 3
    },
    {
        "answerA": "根本不能",
        "answerB": "很少会",
        "answerC": "有时会",
        "answerD": "经常会",
        "answerE": "总是会",
        "asnwerAScore": 1,
        "asnwerBScore": 2,
        "asnwerCScore": 3,
        "asnwerDScore": 4,
        "asnwerEScore": 5,
        "id": "d79abd90-0d07-4591-8d4d-781dd12a4206",
        "num": 89,
        "question": "您会主动寻求他人的支持和帮助吗？",
        "type": 3
    },
    {
        "answerA": "从不",
        "answerB": "已戒烟",
        "answerC": "不是每天吸烟",
        "answerD": "每天1包以内",
        "answerE": "每天1包以上",
        "asnwerAScore": 5,
        "asnwerBScore": 4,
        "asnwerCScore": 3,
        "asnwerDScore": 2,
        "asnwerEScore": 1,
        "id": "aea0c3a0-8caf-4f67-8e85-cdb1093d595a",
        "num": 90,
        "question": "您吸烟吗？",
        "type": 4
    },
    {
        "answerA": "从不",
        "answerB": "很少",
        "answerC": "有时",
        "answerD": "经常",
        "answerE": "总是",
        "asnwerAScore": 5,
        "asnwerBScore": 4,
        "asnwerCScore": 3,
        "asnwerDScore": 2,
        "asnwerEScore": 1,
        "id": "68d76011-e86d-40c3-94e4-55c931acb1b2",
        "num": 91,
        "question": "您是否接触二手烟？",
        "type": 4
    },
    {
        "answerA": "从不",
        "answerB": "每周2次以内",
        "answerC": "每周3-4次",
        "answerD": "每周5-6次",
        "answerE": "每天都喝",
        "asnwerAScore": 5,
        "asnwerBScore": 4,
        "asnwerCScore": 3,
        "asnwerDScore": 2,
        "asnwerEScore": 1,
        "id": "db74a9a6-9661-4a23-91b5-d8e3ac8c7aeb",
        "num": 92,
        "question": "您的饮酒频率？",
        "type": 4
    },
    {
        "answerA": "从不",
        "answerB": "1两以内",
        "answerC": "1-2两",
        "answerD": "3-4两",
        "answerE": "5两以上",
        "asnwerAScore": 5,
        "asnwerBScore": 4,
        "asnwerCScore": 3,
        "asnwerDScore": 2,
        "asnwerEScore": 1,
        "id": "5ccdd052-3858-4adb-ace9-c3b5d7786db1",
        "num": 93,
        "question": "您平均每次喝几两酒？（1两相当于50ml白酒，100ml红酒，300ml啤酒）",
        "type": 4
    },
    {
        "answerA": "很不规律",
        "answerB": "较不规律",
        "answerC": "一般",
        "answerD": "较规律",
        "answerE": "很规律",
        "asnwerAScore": 1,
        "asnwerBScore": 2,
        "asnwerCScore": 3,
        "asnwerDScore": 4,
        "asnwerEScore": 5,
        "id": "4099d21e-46e6-4271-8133-19d93059a21d",
        "num": 94,
        "question": "您的生活作息是否规律正常？",
        "type": 4
    },
    {
        "answerA": "从不",
        "answerB": "1-2次",
        "answerC": "3-4次",
        "answerD": "5-6次",
        "answerE": "每天锻炼",
        "asnwerAScore": 1,
        "asnwerBScore": 2,
        "asnwerCScore": 3,
        "asnwerDScore": 4,
        "asnwerEScore": 5,
        "id": "e19d3828-6b14-482a-aba9-3e9007348e3d",
        "num": 95,
        "question": "您每周锻炼几次？",
        "type": 4
    },
    {
        "answerA": "从不",
        "answerB": "<30分钟",
        "answerC": "30-60分钟",
        "answerD": "1-2小时",
        "answerE": ">2小时",
        "asnwerAScore": 1,
        "asnwerBScore": 2,
        "asnwerCScore": 3,
        "asnwerDScore": 4,
        "asnwerEScore": 5,
        "id": "660f5e9a-557a-4406-a134-624adc22f221",
        "num": 96,
        "question": "您每次锻炼时间为多久？",
        "type": 4
    },
    {
        "answerA": "<4小时 ",
        "answerB": "4-5小时",
        "answerC": "5-7小时",
        "answerD": "7-9小时",
        "answerE": ">9小时",
        "asnwerAScore": 1,
        "asnwerBScore": 2,
        "asnwerCScore": 3,
        "asnwerDScore": 4,
        "asnwerEScore": 5,
        "id": "f258a9b0-0580-45fe-a175-63df0cb90ee0",
        "num": 97,
        "question": "您每天平均睡眠时间(不等于卧床时间)？",
        "type": 4
    },
    {
        "answerA": "很差",
        "answerB": "较差",
        "answerC": "一般",
        "answerD": "较好",
        "answerE": "很好",
        "asnwerAScore": 1,
        "asnwerBScore": 2,
        "asnwerCScore": 3,
        "asnwerDScore": 4,
        "asnwerEScore": 5,
        "id": "f4f8b033-1261-436c-9a89-9c42a763fba6",
        "num": 98,
        "question": "您最近睡眠质量如何？",
        "type": 4
    },
    {
        "answerA": "没有",
        "answerB": "偶尔",
        "answerC": "有时",
        "answerD": "经常",
        "answerE": "总是",
        "asnwerAScore": 5,
        "asnwerBScore": 4,
        "asnwerCScore": 3,
        "asnwerDScore": 2,
        "asnwerEScore": 1,
        "id": "2e390e74-2896-48fb-a26d-e5cd779357c7",
        "num": 99,
        "question": "您最近是否熬夜过？",
        "type": 4
    },
    {
        "answerA": "无",
        "answerB": "很少",
        "answerC": "一般",
        "answerD": "很多",
        "answerE": "非常多",
        "asnwerAScore": 5,
        "asnwerBScore": 4,
        "asnwerCScore": 3,
        "asnwerDScore": 2,
        "asnwerEScore": 1,
        "id": "0782dbf1-6433-4509-9978-af5efb81f53b",
        "num": 100,
        "question": "您的工作（学习）环境中是否存在危险因素？",
        "type": 4
    },
    {
        "answerA": "不工作",
        "answerB": "脑力工作为主",
        "answerC": "轻体力劳动",
        "answerD": "中度体力劳动",
        "answerE": "重体力劳动",
        "asnwerAScore": 5,
        "asnwerBScore": 4,
        "asnwerCScore": 3,
        "asnwerDScore": 2,
        "asnwerEScore": 1,
        "id": "306070cb-ea98-480c-b35c-c3887b826bee",
        "num": 101,
        "question": "您工作中的体力强度?",
        "type": 4
    },
    {
        "answerA": "<6小时",
        "answerB": "6~8小时",
        "answerC": "8~10小时",
        "answerD": "8-12小时",
        "answerE": "12小时以上",
        "asnwerAScore": 5,
        "asnwerBScore": 4,
        "asnwerCScore": 3,
        "asnwerDScore": 2,
        "asnwerEScore": 1,
        "id": "6c62fc6b-fc79-4c83-9ccc-b00baf12f94e",
        "num": 102,
        "question": "您平均每天工作多长时间： 小时",
        "type": 4
    },
    {
        "answerA": "没有",
        "answerB": "很轻",
        "answerC": "中等",
        "answerD": "偏重",
        "answerE": "严重",
        "asnwerAScore": 5,
        "asnwerBScore": 4,
        "asnwerCScore": 3,
        "asnwerDScore": 2,
        "asnwerEScore": 1,
        "id": "ff833285-de9a-4786-911d-73a3bff978cb",
        "num": 103,
        "question": "您平时工作压力大吗？",
        "type": 4
    },
    {
        "answerA": "很不满意",
        "answerB": "较不满意",
        "answerC": "一般",
        "answerD": "较满意",
        "answerE": "很满意",
        "asnwerAScore": 1,
        "asnwerBScore": 2,
        "asnwerCScore": 3,
        "asnwerDScore": 4,
        "asnwerEScore": 5,
        "id": "e60be28e-e4b7-4c9e-98e6-f58255342d1c",
        "num": 104,
        "question": "您对生活地区的环境（污染）是否满意？",
        "type": 4
    },
    {
        "answerA": "很不满意",
        "answerB": "较不满意",
        "answerC": "一般",
        "answerD": "较满意",
        "answerE": "很满意",
        "asnwerAScore": 1,
        "asnwerBScore": 2,
        "asnwerCScore": 3,
        "asnwerDScore": 4,
        "asnwerEScore": 5,
        "id": "012fa674-9e5d-4592-9328-5fbdca8645da",
        "num": 105,
        "question": "您对生活地区的噪声控制是否满意？",
        "type": 4
    }
],
    "success" : true
}